//! Generates cross-language test vectors into tests/vectors/v0_1.json.
//!
//! Uses a FIXED secret key so the Ed25519 signatures are reproducible
//! (Ed25519 is deterministic, RFC 8032). The vectors let a Python (or any other)
//! implementation prove its deterministic Protobuf encoding matches prost's:
//!
//!   1. decode `wire_hex`
//!   2. clear the signature field, re-serialize deterministically
//!   3. assert it equals `proto_canonical_hex`   <-- the canonicalization cross-check
//!   4. verify Ed25519 over (domain || canonical) with `pubkey_hex`
//!
//! Run: `cargo run --example gen_vectors`

use earthnet_protocol::{
    sign, ConfirmedEvent, EvidenceKind, Location, Observation, Signed, SourceType, PROTOCOL_VERSION,
};
use ed25519_dalek::SigningKey;
use prost::Message;
use std::fs;
use std::path::Path;

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn fixed_key(seed: u8) -> SigningKey {
    SigningKey::from_bytes(&[seed; 32])
}

/// Builds one vector JSON object from an already-signed message.
fn vector_json<T: Signed>(name: &str, msg: &T) -> String {
    let wire = msg.encode_to_vec();
    let mut bare = msg.clone();
    bare.set_signature(Vec::new());
    let canonical = bare.encode_to_vec();
    let domain = std::str::from_utf8(T::DOMAIN).unwrap();
    format!(
        "    {{\n      \"name\": \"{}\",\n      \"domain\": \"{}\",\n      \"pubkey_hex\": \"{}\",\n      \"signature_hex\": \"{}\",\n      \"proto_canonical_hex\": \"{}\",\n      \"wire_hex\": \"{}\"\n    }}",
        name,
        domain,
        hex(msg.pubkey()),
        hex(msg.signature()),
        hex(&canonical),
        hex(&wire),
    )
}

fn main() {
    let okey = fixed_key(7);
    let mut obs = Observation {
        protocol_version: PROTOCOL_VERSION,
        observation_id: vec![0xAB; 16],
        pubkey: okey.verifying_key().to_bytes().to_vec(),
        source_type: SourceType::Phone as i32,
        source_id: String::new(),
        captured_at_ns: 1_719_600_000_000_000_000,
        clock_uncert_ms: 20,
        location: Some(Location {
            geohash: "66jd2".into(),
            precision_m: 2400,
        }),
        sta_lta_ratio: 7.5,
        p_wave_detected: true,
        estimated_pga: 0.012,
        reported_magnitude: 0.0,
        signature: Vec::new(),
    };
    sign(&okey, &mut obs);

    let ekey = fixed_key(11);
    let mut evt = ConfirmedEvent {
        protocol_version: PROTOCOL_VERSION,
        event_id: vec![0xCD; 16],
        pubkey: ekey.verifying_key().to_bytes().to_vec(),
        origin_time_ns: 1_719_600_000_000_000_000,
        issued_at_ns: 1_719_600_000_300_000_000,
        epicenter: Some(Location {
            geohash: "66jd2k".into(),
            precision_m: 600,
        }),
        depth_km: 35.0,
        magnitude: 6.2,
        magnitude_uncert: 0.3,
        evidence: EvidenceKind::Official as i32,
        num_observations: 3,
        obs_ids: vec![vec![0xAB; 16], vec![0x01; 16]],
        supersedes: Vec::new(),
        tier: 0, // UNSPECIFIED — keeps the v0.1 vector byte-identical
        signature: Vec::new(),
        attestations: Vec::new(),
    };
    sign(&ekey, &mut evt);

    let json = format!(
        "{{\n  \"version\": \"0.1\",\n  \"note\": \"Generated by `cargo run --example gen_vectors`. Fixed keys; Ed25519 is deterministic.\",\n  \"vectors\": [\n{},\n{}\n  ]\n}}\n",
        vector_json("observation", &obs),
        vector_json("confirmed_event", &evt),
    );

    let path = Path::new("tests/vectors/v0_1.json");
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, &json).unwrap();
    eprintln!("wrote {}", path.display());

    // Echo the locking constants for the regression test.
    println!(
        "OBS_CANONICAL={}",
        hex(&{
            let mut b = obs.clone();
            b.signature = Vec::new();
            b.encode_to_vec()
        })
    );
    println!("OBS_SIG={}", hex(&obs.signature));
    println!(
        "EVT_CANONICAL={}",
        hex(&{
            let mut b = evt.clone();
            b.signature = Vec::new();
            b.encode_to_vec()
        })
    );
    println!("EVT_SIG={}", hex(&evt.signature));
}
